// Generated by CodiumAI

import { createMessage } from "./session";

describe("createMessage", () => {
  // Test that the 'createMessage' function returns a message object with default values when no override is provided.
  it("should return a message object with default values when no override is provided", () => {
    const message = createMessage({});
    expect(message.id).toBeDefined();
    expect(message.date).toBeDefined();
    expect(message.role).toBe("user");
    expect(message.content).toBe("");
  });
});
